param location string
param tags object
param suffix string

param skuName string = 'Basic'
param anonymousPullEnabled bool = true

resource acr 'Microsoft.ContainerRegistry/registries@2026-03-01-preview' = {
  name: 'acrcnr${suffix}'
  location: location
  tags: tags
  sku: {
    name: skuName
  }
  properties: {
    adminUserEnabled: false
    publicNetworkAccess: 'Enabled'
    anonymousPullEnabled: anonymousPullEnabled
    roleAssignmentMode: 'AbacRepositoryPermissions'
    autoGeneratedDomainNameLabelScope: 'SubscriptionReuse'
  }
}

output name string = acr.name
